<?php
require_once __DIR__ . '/vendor/autoload.php';
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

define('SSO_SERVICE', 'http://127.0.0.1:20212');

function sselogin_help($path, $arg) {
    switch ($path) {
        case 'admin/help#sselogin':
            return '<p>'.t('同济大学软件学院教师登录模块，使用前请在设置里面填好教师白名单');
            break;
    }
}

function sselogin_menu() {
    $items = array();

    //登录接口
    $items['sselogin/login'] = array(
        'title' => '登录',
        'page callback' => '_sselogin_login',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    //设置菜单
    $items['admin/config/content/sselogin'] = array(
        'title' => '设置教师白名单',
        'description' => 'Configuration for sse_subscription module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('sselogin_config_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
    );


    return $items;
}

//设置菜单
function sselogin_config_form($form, $form_state) {
    $form['teacher'] = array(
        '#type' => 'textarea',
        '#title' => t('教师白名单'),
        '#default_value' => variable_get('teacher', ''),
        '#required' => TRUE,
    );

    return system_settings_form($form);
}


function _sselogin_login() {
    //这里只处理成功的情况
    $session = $_COOKIE['iPlanetDirectoryPro'];

    $userId = '';
    $userName = '';

    //首先验证session的合法性
    $response = Requests::get(constant('SSO_SERVICE')."/session/properties?sessionid=".urlencode($session));
    if ($response->success) {
        $responseJson = json_decode($response->body);
        if ($responseJson->ok) {
            //验证通过，记录工号
            $userId = $responseJson->properties->UserId;
        } else {
            var_dump("统一验证失败");
            return;
        }
    } else {
        var_dump("SSO服务错误");
        return;
    }

    //姓名
    $response = Requests::get(constant('SSO_SERVICE')."/info/student?sessionid=".urlencode($session));
    if ($response->success) {
        $responseJson = json_decode($response->body);
        $userName = $responseJson->info->name;
    } else {
        var_dump("SSO服务错误");
        return;
    }

    //var_dump($userId);
    //var_dump($userName);

    //验证白名单
    $whiteList = explode("\n", variable_get('teacher', ''));
    $whiteList = array_map("trim", $whiteList);
    //var_dump(trim($whiteList[0]));
    //var_dump($whiteList);
    if (!in_array($userId, $whiteList, TRUE)) {
        var_dump("该用户没有权限");
        return;
    }

    //不存在账户则创建账户
    $userName = 'faculty_'.$userId;
    $user_obj = user_load_by_name($userName);
    if (!$user_obj) {
        $new_user = array(
            'name' => 'faculty_'.$userId,
            'mail' => '505968815@qq.com',
            'pass' => user_password(8),
            'status' => 1,
            'init' => '505968815@qq.com',
            'roles' => array(
                DRUPAL_AUTHENTICATED_RID => 'authenticated user',
                3 => '开发者'
            )
        );
        $user_obj = user_save('', $new_user);
        //var_dump('create success!');

    }

    //直接登录
    //var_dump($user_obj);
    //$login_array = array('name' => $user_obj->uid);
    $form_state = array();
    $form_state['uid'] = $user_obj->uid;
    user_login_submit(array(), $form_state);
    //var_dump("Login Success!");

    drupal_goto("http://ssedev.tongji.edu.cn/zh/admin/dashboard");
}
