<?php
require_once __DIR__ . '/vendor/autoload.php';
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

define('BASE_URL', 'http://ssedev.tongji.edu.cn');
define('SSO_SERVICE', 'http://127.0.0.1:20212');

function sselogin_help($path, $arg) {
    switch ($path) {
        case 'admin/help#sselogin':
            return '<p>'.t('同济大学软件学院教师登录模块，使用前请在设置里面填好教师白名单');
            break;
    }
}

function sselogin_menu() {
    $items = array();

    $items['sselogin/login'] = array(
        'title' => '登录',
        'page callback' => '_sselogin_login',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function _sselogin_login() {
    //这里只处理成功的情况
    $session = $_COOKIE['iPlanetDirectoryPro'];

    $userId = '';
    $userName = '';

    //首先验证session的合法性
    $response = Requests::get(constant('SSO_SERVICE')."/session/properties?sessionid=".urlencode($session));
    if ($response->success) {
        $responseJson = json_decode($response->body);
        if ($responseJson->ok) {
            //验证通过，记录工号
            $userId = $responseJson->properties->UserId;
        } else {
            var_dump("统一验证失败");
            return;
        }
    } else {
        var_dump("SSO服务错误");
        return;
    }

    //姓名
    $response = Requests::get(constant('SSO_SERVICE')."/info/student?sessionid=".urlencode($session));
    if ($response->success) {
        $responseJson = json_decode($response->body);
        $userName = $responseJson->info->name;
    } else {
        var_dump("SSO服务错误");
        return;
    }

    var_dump($userId);
    var_dump($userName);

    //验证白名单

    //不存在账户则登录

    //直接登录


    //drupal_goto("http://www.baidu.com");
}
